before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: CW+8cK3XNSoBSI1o7iufnRbuKQj/dx8aMlkngQKbz1EagCmF5kkbrXNS/6K7ztJpGo31L0gM+ZRkfQDRg9v3hcy7Z0d5AB6SGVBCs18WRnbB5a/JOV4A+T9u+jxbXGXea8KppdZBjyoxr1xU4O4KOzDqrkbewV2K8ACal4h6bq/k3tBAQM1k/gqUeCiWmjeDgfIMpPTMyTJvVZrAqjMnycWFqYI+bQlTsyub3oUOgwq8RdSQOvC+IfdSa6hiH2tpO4MiliJ5yyKXVAfx3jjreAJNIEpZAkN2Ly0UjqkCavzM4cnQceU3hkJzVOgUugHoPxuc9oYDlHeiWTyot5evrj2Wb3hi1PVLNGdS3WwT/OpqhRa65REnsMwl6SVXP6m9Z8IpATR2KwUjZ3tjpR6qKlC8SUBpYRYjaARx+TdSdbQC0kUyD1hKBz673dRQpUdTGWM4scJQWtWGd49Ec4ChUuOAxy3j/elrQuJXS1MrmtCBz8KbWkJ9HF3wfqIlCDXZ/d7z/p17Zsncj4qo0TB+3iLKTlTPuHE2YkVSYVlvfbLBw40GvuXlZbxthafhnBs8x3+BJp0Z5d6q3/Wv6iG/9nlQZ0qbBzCtC9dsMEUjyCAhmqZ83Pkf44bWk2dhDJzEk/ASpNDA4lskvxliHYUh6izChpYDlaKSeak+3SMQJNk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
